### ISSUE TITLE
Ascii map info?

### ISSUE THREAD

**Issue by ETGrif** [Emdeline/Risk#7]
this is gonna be pretty easy for me to do, but id like yall's input. What info needs to be displayed? i think It'd be the name or color of the current owner of that territory and then the number of soldiers in that territory. Is there something I'm missing?

**Comment by HerrmannRyan** [comment]
Nope. That would be all needed.

**Comment by ETGrif** [comment]
neat

**Comment by ETGrif** [comment]
completed in #10
